[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:$PORT app:app --timeout 120 --workers 1"
healthcheckPath = "/ping"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[deploy.envs]
PORT = "8080" 